services:

  rick-cache-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rick-cache-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    networks:
      - rick-cache-api
  db:
    image: mysql:8.0
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - rick-cache-api

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - rick-cache-api


volumes:
  mysql-data:

networks:
  rick-cache-api:
    driver: bridge